In [3]:
import pandas as pd;
import numpy as np;
import os

datos_bancarios = pd.read_csv('bank-additional.csv', index_col = 0)
datos_bancarios.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,...,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,...,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,...,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,...,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,...,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [4]:
rename_ID = datos_bancarios["id_"]
datos_bancarios.drop("id_",axis = 1,inplace = True)
datos_bancarios['ID'] = rename_ID

He renombrado la columna de "_id" a "ID" para poder ejecutar el merge de manera directa on "ID"

In [5]:
datos_bancarios["ID"].head(3)

0    089b39d8-e4d0-461b-87d4-814d71e0e079
1    e9d37224-cb6f-4942-98d7-46672963d097
2    3f9f49b5-e410-4948-bf6e-f9244f04918b
Name: ID, dtype: object

In [ ]:
### PRUEBAS DE CONCEPTOOOOOOOS ###

job_services = datos_bancarios.loc[datos_bancarios["job"]=="services", ["id_","job", "duration","marital"]]
job_services

In [ ]:
datos_clientes_2012 = pd.read_excel(
    'customer-details.xlsx',
    sheet_name='2012',    
    index_col=0,          
    header=0,
    engine='openpyxl'  # Para archivos .xlsx
)
datos_clientes_2012.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [ ]:
bank_data = datos_bancarios.merge(datos_clientes_2012, how= 'inner', on='ID')

KeyError: 'admin'